package com.xyz.domain;

// Generated 2017-7-18 19:08:25 by Hibernate Tools 3.4.0.CR1

/**
 * XyzCartId generated by hbm2java
 */
public class XyzCartId implements java.io.Serializable {

	private int cartGoodsId;
	private int cartBuyerId;

	public XyzCartId() {
	}

	public XyzCartId(int cartGoodsId, int cartBuyerId) {
		this.cartGoodsId = cartGoodsId;
		this.cartBuyerId = cartBuyerId;
	}

	public int getCartGoodsId() {
		return this.cartGoodsId;
	}

	public void setCartGoodsId(int cartGoodsId) {
		this.cartGoodsId = cartGoodsId;
	}

	public int getCartBuyerId() {
		return this.cartBuyerId;
	}

	public void setCartBuyerId(int cartBuyerId) {
		this.cartBuyerId = cartBuyerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof XyzCartId))
			return false;
		XyzCartId castOther = (XyzCartId) other;

		return (this.getCartGoodsId() == castOther.getCartGoodsId())
				&& (this.getCartBuyerId() == castOther.getCartBuyerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCartGoodsId();
		result = 37 * result + this.getCartBuyerId();
		return result;
	}

}
