package com.xyz.domain;

// Generated 2017-7-18 19:08:25 by Hibernate Tools 3.4.0.CR1

/**
 * XyzCart generated by hbm2java
 */
public class XyzCart implements java.io.Serializable {

	private XyzCartId id;
	private XyzUser xyzUser;
	private XyzGoods xyzGoods;

	public XyzCart() {
	}

	public XyzCart(XyzCartId id, XyzUser xyzUser, XyzGoods xyzGoods) {
		this.id = id;
		this.xyzUser = xyzUser;
		this.xyzGoods = xyzGoods;
	}

	public XyzCartId getId() {
		return this.id;
	}

	public void setId(XyzCartId id) {
		this.id = id;
	}

	public XyzUser getXyzUser() {
		return this.xyzUser;
	}

	public void setXyzUser(XyzUser xyzUser) {
		this.xyzUser = xyzUser;
	}

	public XyzGoods getXyzGoods() {
		return this.xyzGoods;
	}

	public void setXyzGoods(XyzGoods xyzGoods) {
		this.xyzGoods = xyzGoods;
	}

}
