package com.xyz.domain;

// Generated 2017-7-18 19:08:25 by Hibernate Tools 3.4.0.CR1

/**
 * XyzComments generated by hbm2java
 */
public class XyzComments implements java.io.Serializable {

	private Long commentsId;
	private XyzUser xyzUser;
	private Integer commentsScore;

	public XyzComments() {
	}

	public XyzComments(XyzUser xyzUser) {
		this.xyzUser = xyzUser;
	}

	public XyzComments(XyzUser xyzUser, Integer commentsScore) {
		this.xyzUser = xyzUser;
		this.commentsScore = commentsScore;
	}

	public Long getCommentsId() {
		return this.commentsId;
	}

	public void setCommentsId(Long commentsId) {
		this.commentsId = commentsId;
	}

	public XyzUser getXyzUser() {
		return this.xyzUser;
	}

	public void setXyzUser(XyzUser xyzUser) {
		this.xyzUser = xyzUser;
	}

	public Integer getCommentsScore() {
		return this.commentsScore;
	}

	public void setCommentsScore(Integer commentsScore) {
		this.commentsScore = commentsScore;
	}

}
