package com.xyz.domain;

// Generated 2017-7-18 19:08:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * XyzGoods generated by hbm2java
 */
public class XyzGoods implements java.io.Serializable {

	private Integer goodsId;
	private XyzUser xyzUser;
	private XyzType xyzType;
	private String goodsName;
	private int goodsStatus;
	private long goodsPrice;
	private String goodsDescription;
	private String goodsPicture1;
	private String goodsPictrue2;
	private String goodsPicture3;
	private Set xyzOrders = new HashSet(0);
	private Set xyzCarts = new HashSet(0);

	public XyzGoods() {
	}

	public XyzGoods(XyzUser xyzUser, XyzType xyzType, String goodsName,
			int goodsStatus, long goodsPrice, String goodsPicture1) {
		this.xyzUser = xyzUser;
		this.xyzType = xyzType;
		this.goodsName = goodsName;
		this.goodsStatus = goodsStatus;
		this.goodsPrice = goodsPrice;
		this.goodsPicture1 = goodsPicture1;
	}

	public XyzGoods(XyzUser xyzUser, XyzType xyzType, String goodsName,
			int goodsStatus, long goodsPrice, String goodsDescription,
			String goodsPicture1, String goodsPictrue2, String goodsPicture3,
			Set xyzOrders, Set xyzCarts) {
		this.xyzUser = xyzUser;
		this.xyzType = xyzType;
		this.goodsName = goodsName;
		this.goodsStatus = goodsStatus;
		this.goodsPrice = goodsPrice;
		this.goodsDescription = goodsDescription;
		this.goodsPicture1 = goodsPicture1;
		this.goodsPictrue2 = goodsPictrue2;
		this.goodsPicture3 = goodsPicture3;
		this.xyzOrders = xyzOrders;
		this.xyzCarts = xyzCarts;
	}

	public Integer getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	public XyzUser getXyzUser() {
		return this.xyzUser;
	}

	public void setXyzUser(XyzUser xyzUser) {
		this.xyzUser = xyzUser;
	}

	public XyzType getXyzType() {
		return this.xyzType;
	}

	public void setXyzType(XyzType xyzType) {
		this.xyzType = xyzType;
	}

	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public int getGoodsStatus() {
		return this.goodsStatus;
	}

	public void setGoodsStatus(int goodsStatus) {
		this.goodsStatus = goodsStatus;
	}

	public long getGoodsPrice() {
		return this.goodsPrice;
	}

	public void setGoodsPrice(long goodsPrice) {
		this.goodsPrice = goodsPrice;
	}

	public String getGoodsDescription() {
		return this.goodsDescription;
	}

	public void setGoodsDescription(String goodsDescription) {
		this.goodsDescription = goodsDescription;
	}

	public String getGoodsPicture1() {
		return this.goodsPicture1;
	}

	public void setGoodsPicture1(String goodsPicture1) {
		this.goodsPicture1 = goodsPicture1;
	}

	public String getGoodsPictrue2() {
		return this.goodsPictrue2;
	}

	public void setGoodsPictrue2(String goodsPictrue2) {
		this.goodsPictrue2 = goodsPictrue2;
	}

	public String getGoodsPicture3() {
		return this.goodsPicture3;
	}

	public void setGoodsPicture3(String goodsPicture3) {
		this.goodsPicture3 = goodsPicture3;
	}

	public Set getXyzOrders() {
		return this.xyzOrders;
	}

	public void setXyzOrders(Set xyzOrders) {
		this.xyzOrders = xyzOrders;
	}

	public Set getXyzCarts() {
		return this.xyzCarts;
	}

	public void setXyzCarts(Set xyzCarts) {
		this.xyzCarts = xyzCarts;
	}

}
