package com.xyz.domain;

// Generated 2017-7-18 19:08:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * XyzOrder generated by hbm2java
 */
public class XyzOrder implements java.io.Serializable {

	private Long orderId;
	private XyzGoods xyzGoods;
	private XyzUser xyzUserByOrderSellerId;
	private XyzUser xyzUserByOrderBuyerId;
	
	private Date orderTime;
	
	private int orderIscomplete;
	private int orderShow;
	
	private String orderAddress;
	private String orderCelphone;

	public XyzOrder() {
	}

	public XyzOrder(XyzGoods xyzGoods, XyzUser xyzUserByOrderSellerId,
			XyzUser xyzUserByOrderBuyerId, Date orderTime, int orderIscomplete,
			int orderShow, String orderAddress, String orderCelphone) {
		this.xyzGoods = xyzGoods;
		this.xyzUserByOrderSellerId = xyzUserByOrderSellerId;
		this.xyzUserByOrderBuyerId = xyzUserByOrderBuyerId;
		this.orderTime = orderTime;
		this.orderIscomplete = orderIscomplete;
		this.orderShow = orderShow;
		this.orderAddress = orderAddress;
		this.orderCelphone = orderCelphone;
	}

	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public XyzGoods getXyzGoods() {
		return this.xyzGoods;
	}

	public void setXyzGoods(XyzGoods xyzGoods) {
		this.xyzGoods = xyzGoods;
	}

	public XyzUser getXyzUserByOrderSellerId() {
		return this.xyzUserByOrderSellerId;
	}

	public void setXyzUserByOrderSellerId(XyzUser xyzUserByOrderSellerId) {
		this.xyzUserByOrderSellerId = xyzUserByOrderSellerId;
	}

	public XyzUser getXyzUserByOrderBuyerId() {
		return this.xyzUserByOrderBuyerId;
	}

	public void setXyzUserByOrderBuyerId(XyzUser xyzUserByOrderBuyerId) {
		this.xyzUserByOrderBuyerId = xyzUserByOrderBuyerId;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public int getOrderIscomplete() {
		return this.orderIscomplete;
	}

	public void setOrderIscomplete(int orderIscomplete) {
		this.orderIscomplete = orderIscomplete;
	}

	public int getOrderShow() {
		return this.orderShow;
	}

	public void setOrderShow(int orderShow) {
		this.orderShow = orderShow;
	}

	public String getOrderAddress() {
		return this.orderAddress;
	}

	public void setOrderAddress(String orderAddress) {
		this.orderAddress = orderAddress;
	}

	public String getOrderCelphone() {
		return this.orderCelphone;
	}

	public void setOrderCelphone(String orderCelphone) {
		this.orderCelphone = orderCelphone;
	}

}
