package com.xyz.domain;

// Generated 2017-7-18 19:08:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * XyzType generated by hbm2java
 */
public class XyzType implements java.io.Serializable {

	private String typeName;
	private Set xyzGoodses = new HashSet(0);

	public XyzType() {
	}

	public XyzType(String typeName) {
		this.typeName = typeName;
	}

	public XyzType(String typeName, Set xyzGoodses) {
		this.typeName = typeName;
		this.xyzGoodses = xyzGoodses;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Set getXyzGoodses() {
		return this.xyzGoodses;
	}

	public void setXyzGoodses(Set xyzGoodses) {
		this.xyzGoodses = xyzGoodses;
	}

}
