package com.xyz.domain;

// Generated 2017-7-18 19:08:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * XyzUser generated by hbm2java
 */
public class XyzUser implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPassword;
	private String userCelphone;
	private String userAddress;
	private Set xyzOrdersForOrderSellerId = new HashSet(0);
	private Set xyzGoodses = new HashSet(0);
	private Set xyzCommentses = new HashSet(0);
	private Set xyzCarts = new HashSet(0);
	private Set xyzOrdersForOrderBuyerId = new HashSet(0);

	public XyzUser() {
	}

	public XyzUser(String userName, String userPassword, String userCelphone,
			String userAddress) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.userCelphone = userCelphone;
		this.userAddress = userAddress;
	}

	public XyzUser(String userName, String userPassword, String userCelphone,
			String userAddress, Set xyzOrdersForOrderSellerId, Set xyzGoodses,
			Set xyzCommentses, Set xyzCarts, Set xyzOrdersForOrderBuyerId) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.userCelphone = userCelphone;
		this.userAddress = userAddress;
		this.xyzOrdersForOrderSellerId = xyzOrdersForOrderSellerId;
		this.xyzGoodses = xyzGoodses;
		this.xyzCommentses = xyzCommentses;
		this.xyzCarts = xyzCarts;
		this.xyzOrdersForOrderBuyerId = xyzOrdersForOrderBuyerId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserCelphone() {
		return this.userCelphone;
	}

	public void setUserCelphone(String userCelphone) {
		this.userCelphone = userCelphone;
	}

	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public Set getXyzOrdersForOrderSellerId() {
		return this.xyzOrdersForOrderSellerId;
	}

	public void setXyzOrdersForOrderSellerId(Set xyzOrdersForOrderSellerId) {
		this.xyzOrdersForOrderSellerId = xyzOrdersForOrderSellerId;
	}

	public Set getXyzGoodses() {
		return this.xyzGoodses;
	}

	public void setXyzGoodses(Set xyzGoodses) {
		this.xyzGoodses = xyzGoodses;
	}

	public Set getXyzCommentses() {
		return this.xyzCommentses;
	}

	public void setXyzCommentses(Set xyzCommentses) {
		this.xyzCommentses = xyzCommentses;
	}

	public Set getXyzCarts() {
		return this.xyzCarts;
	}

	public void setXyzCarts(Set xyzCarts) {
		this.xyzCarts = xyzCarts;
	}

	public Set getXyzOrdersForOrderBuyerId() {
		return this.xyzOrdersForOrderBuyerId;
	}

	public void setXyzOrdersForOrderBuyerId(Set xyzOrdersForOrderBuyerId) {
		this.xyzOrdersForOrderBuyerId = xyzOrdersForOrderBuyerId;
	}

}
